### ISSUE TITLE
Change icon of specific program

### ISSUE THREAD

**Issue by NailGit** [kolbusa/stalonetray#24] opened 2023-03-07 12:25 UTC
I'm using stalonetray for many years in FVWM without a problem. I starting now to use blueman-applet. Background of display is dark and icond dark, too. Nothing can see. I'd like to change icon for something more light but I do not understand where the stalonetray takes them? In /usr/share/icons/hicolor there are blueman.png, blueman-active.png, blueman-disabled.png and the same for all sizes. In config stalonetray I set size 32 and then I tried to change these icons 32x32 for anothers but without effect. May be it is possible to make possibility to use my own icons for specific program?

**Comment by kolbusa** [comment] 2023-05-24 03:30
Sorry for a delayed response... the apps are responsible for their own icons and all the drawing. Stalonetray actually 'embeds' their windows inside its own main window and leaves the rest up to the applications.

**Comment by kolbusa** [comment] 2023-08-25 07:41
Closing as not a bug

**Closed by kolbusa** 2023-08-25 07:41 UTC
Labels: notabug

**Comment by michael-nhat** [comment] 2023-11-21 09:13
@kolbusa Sorry, hi, sorry to bother you, I want simulate click to icon of a app on the tray (e.g Goldendict, ...) . Is there way implement in code, to track orders of that icons? and then I will depend of sizes to get the coordinate of the target icon and simulate a click to it?

**Comment by kolbusa** [comment] 2023-11-22 06:26
Hi @michael-nhat. What mechanism are you going to use to simulate a click? It should be possible to locate Goldendict window by walking the window tree from root, but modern toolkits filter out synthetic mouse events for security reasons. This was also briefly discussed in #9.

**Comment by michael-nhat** [comment] 2023-11-22 07:46
The command `xwininfo -root -tree` seem tobe enough for me, it contain coordinate of icons windows and I could use `xte` to give a click. So no need to change source code. I have googled so much but the solution is simpler than I thought. Thank you so much @kolbusa !
